app9/urls.py
from django.urls import path
from app9 import views
app_name="app9"


urlpatterns = [
    path('register/',views.register,name="register"),
    path("profile/",views.profile,name="profile"),
]

redirect/urls.py
from django.contrib import admin
from django.urls import path,include
import app9
from app9 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('base',views.base,name='base'),
    path('app9/',include("app9.urls")),
]

app9/models.py
from django.db import models

# Create your models here.

app9/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.mail import send_mail

# Create your views here.

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"app9/home.html")

def profile(request):
    name="rocky"
    return render(request,"app9/profile.html",{'name':name})

def register(request):
    if request.method=="POST":
        first_name=request.POST.get("first_name")
        last_name=request.POST.get("last_name")
        email=request.POST.get("email")
        password=request.POST.get("password")
        phonenumber=request.POST.get("phone number")
        gender=request.POST.get("gender")
        DOB=request.POST.get("DOB")
        send_mail("thanks for registration","hello {} {}\n thanks for tregistering ".format(first_name,last_name),
        "roopendrark@gmail.com",[email,],fail_silently=False)
        return redirect("home")
    return render(request,"app9/registration.html")

templates/app9/home.html
{% extends "base.html" %}

{% block title  %}

   <title>home page</title>
{% endblock  %}

{% block content %}
  <div class="container">
      <div class="jumbotron">
          <center><h1>welcome to home page</h1></center>
      </div>
  </div>
{% endblock  %}

templates/app9/profile.html
{% extends "base.html" %}

{% block title  %}

   <title>profile page</title>
{% endblock  %}

{% block content %}
  <div class="container">
      <div class="jumbotron">
          <center><h1>welcome to {{name}} profile page</h1></center>
      </div>
  </div>
{% endblock  %}

templates/app9/registration.html
{% extends "base.html" %}

{% block title %}
  <title>registration page</title>
{% endblock  %}

{% block content  %}
    <div class="container">
        <div class="jumbotron">
            <div class="container"><center><h2>Register here</h2></center></div>
            <form method="POST" class="form-group" align="center">
                {% csrf_token %}
                firstname:   <input type="text" class="form-control" name="first_name" id="first_name" required><br><br>
                 lastname:   <input type="text" class="form-control" name="last_name" id="last_name" required><br><br>
                    email:   <input type="email" class="form-control" name="email" id="email" required><br><br>
                 password:   <input type="password" class="form-control" name="password" id="password" required><br><br>
                phonenumber: <input type="number" class="form-control" name="phonenumber" id="phonenumber" pattern="[6-9]\d{9}" required><br><br>
                
                    <legend >GENDER</legend>
                    <input type="radio" name="gender">male
                    <input type="radio" name="gender">female
                    </br><br>

                    
                        <legend >DOB</legend>
                        <input type="date" name="DOB"></br></br>
                        <input type="time" name="DOB"></br></br>
                        <br>
                <input type="submit" value="register" class="btn btn-primary">
                        
            </form>
        </div>
    </div>
  
{% endblock  %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   {% block title %}
   <title>base page</title>
   {% endblock  %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
    {% include "partials/_header.html" %}
    {% include "partials/_navbar.html" %}


    {% block content %}
     <div class="container">
         <div class="jumbotron">
             <center><h1>welcome to base page</h1></center>
         </div>

     </div>
      
    {% endblock  %}

    {% include "partials/_footer.html" %}
    
</body>
</html>

templates/partials/_footer.html
<div class="alert alert-primary" role="alert">
    <center>footer</center>
</div>

templates/partials/_header.html
<div class="alert alert-primary" role="alert">
    <center>header</center>
</div>

templates/partials/_navbar.html
<div class="container">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'home' %}">home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'app9:profile' %}">profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'app9:register' %}">register</a>
        </li>



    </ul>
</div>